# Generated by Django 3.2.5 on 2022-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
